# Generated by Django 5.2.17 on 2026-09-27 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('template_code', models.CharField(default='fruit_story', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('script', 'Script'), ('images', 'Images'), ('rendering', 'Rendering'), ('complete', 'Complete'), ('failed', 'Failed')], default='draft', max_length=16)),
                ('target_duration_seconds', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('script', models.TextField(blank=True)),
                ('image_prompt', models.TextField(blank=True)),
                ('video_prompt', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=3)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='projects.project')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('project', 'position')},
            },
        ),
    ]
