# Generated by Django 5.2.17 on 2026-09-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_character_storyboardimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='aspect_ratio',
            field=models.CharField(default='9:16', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_credit_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='quality_tier',
            field=models.CharField(default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='voice_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
