# Generated by Django 5.2.17 on 2026-09-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_aspect_ratio_project_estimated_credit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='voice_preset',
            field=models.CharField(default='warm_female', max_length=40),
        ),
    ]
