# Generated by Django 5.2.17 on 2026-09-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_voice_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='story_idea',
            field=models.TextField(blank=True),
        ),
    ]
