# Generated by Django 5.2.17 on 2026-09-27 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_code', models.CharField(default='ltx-fast', max_length=64)),
                ('resolution', models.CharField(default='720p', max_length=16)),
                ('duration_seconds', models.PositiveIntegerField(default=3)),
                ('estimated_credits', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('provider_job_id', models.CharField(blank=True, max_length=128)),
                ('output_url', models.URLField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='projects.project')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='projects.scene')),
            ],
        ),
    ]
