# Generated by Django 5.2.17 on 2026-10-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0002_generationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='estimated_credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
